### ISSUE TITLE
Turn by object

### ISSUE THREAD

**Issue by ufgo** [astrochili/defold-operator#11]
Now if the camera is tied to an object, it will look straight all the time, and to rotate it, you need to use [manual_control](https://github.com/astrochili/defold-operator#manual_control ), which is quite difficult since you need to take into account the speed of the object. For example, in a racing game, the car is standing still and when turning left or right, if you send a manual_control message, the camera will turn while only the wheels will turn, and not the car itself.

**Comment by astrochili** [comment]
Added the `follow_object_rotation` property in [1.5.0](https://github.com/astrochili/defold-operator/releases).
