### ISSUE TITLE
The camera stays on the place after reloading scene

### ISSUE THREAD

**Issue by ufgo** [astrochili/defold-operator#13]
The camera stays in the same place after restarting the collection and disconnects from the object.
[operator bug.zip](https://github.com/astrochili/defold-operator/files/12574767/operator.bug.zip)

**Comment by astrochili** [comment]
Fixed!

The issue was that the url of the old camera matched the url of the new camera. Normally this should not happen, but in your case the camera is inside the proxy collection and has the same url after loading the same collection.
